[2022-06-16 10:32:02,615] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: analytics.getdata scheduled__2022-05-09T00:00:00+00:00 [queued]>
[2022-06-16 10:32:02,797] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: analytics.getdata scheduled__2022-05-09T00:00:00+00:00 [queued]>
[2022-06-16 10:32:02,811] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-16 10:32:02,833] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-16 10:32:02,873] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-16 10:32:03,199] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): getdata> on 2022-05-09 00:00:00+00:00
[2022-06-16 10:32:03,272] {standard_task_runner.py:52} INFO - Started process 3545 to run task
[2022-06-16 10:32:03,327] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'analytics', 'getdata', 'scheduled__2022-05-09T00:00:00+00:00', '--job-id', '429', '--raw', '--subdir', 'DAGS_FOLDER/testing_etl.py', '--cfg-path', '/tmp/tmpsuxlpc5_', '--error-file', '/tmp/tmpc8i2bt7d']
[2022-06-16 10:32:03,343] {standard_task_runner.py:80} INFO - Job 429: Subtask getdata
[2022-06-16 10:32:03,907] {task_command.py:370} INFO - Running <TaskInstance: analytics.getdata scheduled__2022-05-09T00:00:00+00:00 [running]> on host fe209149cfc1
[2022-06-16 10:32:04,745] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=analytics
AIRFLOW_CTX_TASK_ID=getdata
AIRFLOW_CTX_EXECUTION_DATE=2022-05-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-09T00:00:00+00:00
[2022-06-16 10:32:04,752] {mysql.py:82} INFO - Executing: SELECT * from Customer_T;
[2022-06-16 10:32:04,827] {base.py:68} INFO - Using connection ID 'mysql_con' for task execution.
[2022-06-16 10:32:04,906] {dbapi.py:213} INFO - Running statement: SELECT * from Customer_T;, parameters: None
[2022-06-16 10:32:04,914] {dbapi.py:221} INFO - Rows affected: 19
[2022-06-16 10:32:05,117] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=analytics, task_id=getdata, execution_date=20220509T000000, start_date=20220616T103202, end_date=20220616T103205
[2022-06-16 10:32:05,307] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-16 10:32:05,680] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
