[2022-06-16 10:31:12,285] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: analytics.getdata scheduled__2022-04-17T00:00:00+00:00 [queued]>
[2022-06-16 10:31:12,585] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: analytics.getdata scheduled__2022-04-17T00:00:00+00:00 [queued]>
[2022-06-16 10:31:12,586] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-16 10:31:12,602] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-16 10:31:12,684] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-16 10:31:13,049] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): getdata> on 2022-04-17 00:00:00+00:00
[2022-06-16 10:31:13,132] {standard_task_runner.py:52} INFO - Started process 3479 to run task
[2022-06-16 10:31:13,227] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'analytics', 'getdata', 'scheduled__2022-04-17T00:00:00+00:00', '--job-id', '407', '--raw', '--subdir', 'DAGS_FOLDER/testing_etl.py', '--cfg-path', '/tmp/tmpl1f7d11p', '--error-file', '/tmp/tmpmypujf9m']
[2022-06-16 10:31:13,266] {standard_task_runner.py:80} INFO - Job 407: Subtask getdata
[2022-06-16 10:31:14,107] {task_command.py:370} INFO - Running <TaskInstance: analytics.getdata scheduled__2022-04-17T00:00:00+00:00 [running]> on host fe209149cfc1
[2022-06-16 10:31:14,897] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=analytics
AIRFLOW_CTX_TASK_ID=getdata
AIRFLOW_CTX_EXECUTION_DATE=2022-04-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-17T00:00:00+00:00
[2022-06-16 10:31:14,898] {mysql.py:82} INFO - Executing: SELECT * from Customer_T;
[2022-06-16 10:31:14,930] {base.py:68} INFO - Using connection ID 'mysql_con' for task execution.
[2022-06-16 10:31:14,971] {dbapi.py:213} INFO - Running statement: SELECT * from Customer_T;, parameters: None
[2022-06-16 10:31:14,973] {dbapi.py:221} INFO - Rows affected: 19
[2022-06-16 10:31:15,010] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=analytics, task_id=getdata, execution_date=20220417T000000, start_date=20220616T103112, end_date=20220616T103115
[2022-06-16 10:31:15,093] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-16 10:31:15,320] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
