[2022-06-17 07:25:51,769] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl-processing.test manual__2022-06-17T07:25:47.180517+00:00 [queued]>
[2022-06-17 07:25:51,854] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl-processing.test manual__2022-06-17T07:25:47.180517+00:00 [queued]>
[2022-06-17 07:25:51,856] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 07:25:51,857] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-17 07:25:51,868] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 07:25:51,957] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): test> on 2022-06-17 07:25:47.180517+00:00
[2022-06-17 07:25:51,966] {standard_task_runner.py:52} INFO - Started process 164 to run task
[2022-06-17 07:25:51,975] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl-processing', 'test', 'manual__2022-06-17T07:25:47.180517+00:00', '--job-id', '503', '--raw', '--subdir', 'DAGS_FOLDER/testing_etl.py', '--cfg-path', '/tmp/tmphdk0zh18', '--error-file', '/tmp/tmp5_3duq0j']
[2022-06-17 07:25:51,977] {standard_task_runner.py:80} INFO - Job 503: Subtask test
[2022-06-17 07:25:52,208] {task_command.py:370} INFO - Running <TaskInstance: etl-processing.test manual__2022-06-17T07:25:47.180517+00:00 [running]> on host fe209149cfc1
[2022-06-17 07:25:52,955] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl-processing
AIRFLOW_CTX_TASK_ID=test
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T07:25:47.180517+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-17T07:25:47.180517+00:00
[2022-06-17 07:25:54,045] {base.py:68} INFO - Using connection ID 'mysql_con' for task execution.
[2022-06-17 07:25:54,126] {xcom.py:585} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-06-17 07:25:54,127] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/testing_etl.py", line 33, in get_source_data
    context['ti'].xcom_push(key='source_db_result',value=source_db_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2392, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 197, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 582, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2022-06-17 07:25:54,160] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl-processing, task_id=test, execution_date=20220617T072547, start_date=20220617T072551, end_date=20220617T072554
[2022-06-17 07:25:54,196] {standard_task_runner.py:97} ERROR - Failed to execute job 503 for task test (Object of type DataFrame is not JSON serializable; 164)
[2022-06-17 07:25:54,237] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-17 07:25:54,316] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
