[2022-06-16 10:30:54,553] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: analytics.getdata scheduled__2022-04-09T00:00:00+00:00 [queued]>
[2022-06-16 10:30:54,712] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: analytics.getdata scheduled__2022-04-09T00:00:00+00:00 [queued]>
[2022-06-16 10:30:54,713] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-16 10:30:54,714] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-16 10:30:54,719] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-16 10:30:55,195] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): getdata> on 2022-04-09 00:00:00+00:00
[2022-06-16 10:30:55,367] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'analytics', 'getdata', 'scheduled__2022-04-09T00:00:00+00:00', '--job-id', '399', '--raw', '--subdir', 'DAGS_FOLDER/testing_etl.py', '--cfg-path', '/tmp/tmp5ub0jaeu', '--error-file', '/tmp/tmp42yj75fj']
[2022-06-16 10:30:55,345] {standard_task_runner.py:52} INFO - Started process 3452 to run task
[2022-06-16 10:30:55,381] {standard_task_runner.py:80} INFO - Job 399: Subtask getdata
[2022-06-16 10:30:56,496] {task_command.py:370} INFO - Running <TaskInstance: analytics.getdata scheduled__2022-04-09T00:00:00+00:00 [running]> on host fe209149cfc1
[2022-06-16 10:30:57,664] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=analytics
AIRFLOW_CTX_TASK_ID=getdata
AIRFLOW_CTX_EXECUTION_DATE=2022-04-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-09T00:00:00+00:00
[2022-06-16 10:30:57,681] {mysql.py:82} INFO - Executing: SELECT * from Customer_T;
[2022-06-16 10:30:57,838] {base.py:68} INFO - Using connection ID 'mysql_con' for task execution.
[2022-06-16 10:30:57,943] {dbapi.py:213} INFO - Running statement: SELECT * from Customer_T;, parameters: None
[2022-06-16 10:30:57,955] {dbapi.py:221} INFO - Rows affected: 19
[2022-06-16 10:30:58,235] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=analytics, task_id=getdata, execution_date=20220409T000000, start_date=20220616T103054, end_date=20220616T103058
[2022-06-16 10:30:58,457] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-16 10:30:59,022] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
